name: Agent Baku
favicon: null
layout_spectrum: 0.7811878428328782
typography_spectrum: 0.6795479150023311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2293844094965607
  lightness: 0.7301771938800812
  saturation: 0.9123420573305339
  rhythmicContrast: 0.6596426891628653
purpose: []
